# EX_01 — Embeddings básicos (ejercicios)

**Notebook de referencia:** `notebook/01_Introduccion_NLP_Embeddings_Basicos.ipynb`

**Tiempo orientativo:** ~30 minutos.


## Actividad 1 — One-hot desde vocabulario

Dado un vocabulario fijo y una frase tokenizada en palabras, construye una matriz one-hot `(seq_len, vocab_size)` sin sklearn (solo NumPy).


In [1]:
import numpy as np

vocab = ["cat", "sat", "mat", "the"]
sentence = ["the", "cat", "sat"]

# Crear diccionario palabra -> índice
word_to_idx = {word: idx for idx, word in enumerate(vocab)}

# Inicializar matriz one-hot
one_hot = np.zeros((len(sentence), len(vocab)), dtype=int)

# Rellenar matriz
for i, word in enumerate(sentence):
    if word in word_to_idx:
        one_hot[i, word_to_idx[word]] = 1

print("Vocabulary:", vocab)
print("\nSentence:", sentence)
print("\nOne-hot matrix:")
print(one_hot)

sentence = ["the", "mat", "sat"]

sentence = ["cat", "sat", "the"]


Vocabulary: ['cat', 'sat', 'mat', 'the']

Sentence: ['the', 'cat', 'sat']

One-hot matrix:
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


## Actividad 2 — Similitud coseno

Implementa `cosine_similarity(a, b)` para vectores 1D y compara dos palabras usando sus filas one-hot (esperado: 0 o 1). Luego discute por qué one-hot no captura similitud semántica.


In [2]:
import numpy as np

# Función cosine similarity
def cosine_similarity(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    
    return dot_product / (norm_a * norm_b)

# Comparar dos palabras usando one-hot vectors
vec_cat = one_hot[1]   # "cat"
vec_sat = one_hot[2]   # "sat"

similarity = cosine_similarity(vec_cat, vec_sat)

print("Vector for 'cat':", vec_cat)
print("Vector for 'sat':", vec_sat)

print("\nCosine similarity:", similarity)


Vector for 'cat': [1 0 0 0]
Vector for 'sat': [0 1 0 0]

Cosine similarity: 0.0


## Actividad 3 — Ventana con Gensim (lectura + entrenamiento mínimo)

Entrena un `Word2Vec` minúsculo sobre `sentences` (lista de listas de tokens) con `vector_size=8`, `window=2`, `min_count=1`. Imprime el vector de una palabra y la similitud entre dos.

*Hint:* `from gensim.models import Word2Vec`.


In [3]:
from gensim.models import Word2Vec

sentences = [
    ["the", "cat", "sat", "on", "the", "mat"],
    ["the", "dog", "sat", "on", "the", "log"],
]

# Entrenar modelo Word2Vec
model = Word2Vec(
    sentences,
    vector_size=8,
    window=2,
    min_count=1,
    workers=1
)

# Vector de una palabra
cat_vector = model.wv["cat"]

print("Vector for 'cat':")
print(cat_vector)

# Similitud entre palabras
similarity = model.wv.similarity("cat", "dog")

print("\nSimilarity between 'cat' and 'dog':")
print(similarity)

Vector for 'cat':
[ 0.06227572  0.11541429 -0.10197397  0.05619748 -0.05171345  0.0103067
  0.10623275 -0.05577721]

Similarity between 'cat' and 'dog':
-0.09075314
