# EX_01 — Embeddings básicos (ejercicios)

**Notebook de referencia:** `notebook/01_Introduccion_NLP_Embeddings_Basicos.ipynb`

**Tiempo orientativo:** ~30 minutos.


## Actividad 1 — One-hot desde vocabulario

Dado un vocabulario fijo y una frase tokenizada en palabras, construye una matriz one-hot `(seq_len, vocab_size)` sin sklearn (solo NumPy).


In [1]:
import numpy as np

vocab = ["cat", "sat", "mat", "the"]

sentence = ["the", "cat", "sat", "the", "mat"] 

# TODO: build index
word_to_idx = {word: idx for idx, word in enumerate(vocab)}

# TODO: build one-hot matrix 
seq_len = len(sentence)
vocab_size = len(vocab)

# Inicializamos una matriz de ceros con las dimensiones correctas
one_hot_matrix = np.zeros((seq_len, vocab_size), dtype=np.float32)

# Rellenamos con un 1 la posición correspondiente a cada token de la frase
for row_idx, word in enumerate(sentence):
    if word in word_to_idx:
        col_idx = word_to_idx[word]
        one_hot_matrix[row_idx, col_idx] = 1.0

print("=== MAPEO DEL VOCABULARIO ===")
print(word_to_idx)

print("\n=== MATRIZ ONE-HOT RESULTANTE ===")
print(f"Dimensiones de la matriz (seq_len, vocab_size): {one_hot_matrix.shape}")
print(one_hot_matrix)


=== MAPEO DEL VOCABULARIO ===
{'cat': 0, 'sat': 1, 'mat': 2, 'the': 3}

=== MATRIZ ONE-HOT RESULTANTE ===
Dimensiones de la matriz (seq_len, vocab_size): (5, 4)
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


## Actividad 2 — Similitud coseno

Implementa `cosine_similarity(a, b)` para vectores 1D y compara dos palabras usando sus filas one-hot (esperado: 0 o 1). Luego discute por qué one-hot no captura similitud semántica.


In [2]:
import numpy as np

# TODO: cosine_similarity 
def cosine_similarity(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    
    if norm_u == 0 or norm_v == 0:
        return 0.0
    return dot_product / (norm_u * norm_v)

# TODO: pick two rows from your one-hot matrix
# Tomamos la fila 0 (representa a "the") y la fila 1 (representa a "cat")
fila_0 = one_hot_matrix[0]  # Vector para "the"
fila_1 = one_hot_matrix[1]  # Vector para "cat"

# Calcular la similitud entre ambas representaciones
similitud = cosine_similarity(fila_0, fila_1)

print("=== EVALUACIÓN DE SIMILITUD COSENO ===")
print(f"Vector A (Fila 0 - 'the'): {fila_0}")
print(f"Vector B (Fila 1 - 'cat'): {fila_1}")
print(f"Similitud Coseno calculada: {similitud:.4f}")
print("\nNota teórica: El resultado es 0.0 debido a que las representaciones")
print("One-Hot son ortogonales; no capturan relaciones semánticas entre palabras.")


=== EVALUACIÓN DE SIMILITUD COSENO ===
Vector A (Fila 0 - 'the'): [0. 0. 0. 1.]
Vector B (Fila 1 - 'cat'): [1. 0. 0. 0.]
Similitud Coseno calculada: 0.0000

Nota teórica: El resultado es 0.0 debido a que las representaciones
One-Hot son ortogonales; no capturan relaciones semánticas entre palabras.


## Actividad 3 — Ventana con Gensim (lectura + entrenamiento mínimo)

Entrena un `Word2Vec` minúsculo sobre `sentences` (lista de listas de tokens) con `vector_size=8`, `window=2`, `min_count=1`. Imprime el vector de una palabra y la similitud entre dos.

*Hint:* `from gensim.models import Word2Vec`.


In [3]:
from gensim.models import Word2Vec

sentences = [
    ["the", "cat", "sat", "on", "the", "mat"],
    ["the", "dog", "sat", "on", "the", "log"],
]

# TODO... 
model_w2v = Word2Vec(
    sentences=sentences,
    vector_size=8,   
    window=2,        
    min_count=1,     
    workers=1,
    seed=42          
)

# Extraer el vector de una palabra
word_target = "cat"
vector_cat = model_w2v.wv[word_target]

# Calcular la similitud semántica latente entre dos palabras
w1, w2 = "cat", "dog"
similitud_semantica = model_w2v.wv.similarity(w1, w2)

print("=== ENTRENAMIENTO WORD2VEC (GENSIM) ===")
print(f"Vector denso de la palabra '{word_target}' (Dimensión {len(vector_cat)}):")
print(vector_cat)

print("\n=== SIMILITUD SEMÁNTICA PRODUCIDA ===")
print(f"Similitud entre '{w1}' y '{w2}': {similitud_semantica:.4f}")
print("\nNota teórica: A diferencia de One-Hot, Word2Vec asigna una puntuación")
print("distinta de cero porque aprende que ambas palabras comparten contextos similares.")


=== ENTRENAMIENTO WORD2VEC (GENSIM) ===
Vector denso de la palabra 'cat' (Dimensión 8):
[ 0.04447974  0.06959587  0.06497486 -0.07634033 -0.03402349 -0.00831975
 -0.00055212 -0.11404906]

=== SIMILITUD SEMÁNTICA PRODUCIDA ===
Similitud entre 'cat' y 'dog': 0.0902

Nota teórica: A diferencia de One-Hot, Word2Vec asigna una puntuación
distinta de cero porque aprende que ambas palabras comparten contextos similares.
