# EX_01 — Embeddings básicos (ejercicios)

**Notebook de referencia:** `notebook/01_Introduccion_NLP_Embeddings_Basicos.ipynb`

**Tiempo orientativo:** ~30 minutos.


## Actividad 1 — One-hot desde vocabulario

Dado un vocabulario fijo y una frase tokenizada en palabras, construye una matriz one-hot `(seq_len, vocab_size)` sin sklearn (solo NumPy).


In [1]:
import numpy as np

vocab = ["cat", "sat", "mat", "the"]
# Cambiamos un poco la frase para usar todo el vocabulario y repetir palabras
sentence = ["the", "cat", "sat", "the", "mat"] 

# 1. Construimos el índice (Diccionario: Palabra -> Posición en el vocabulario)
word_to_idx = {word: i for i, word in enumerate(vocab)}

# 2. Inicializamos la matriz de ceros con la forma (seq_len, vocab_size)
seq_len = len(sentence)
vocab_size = len(vocab)
one_hot_matrix = np.zeros((seq_len, vocab_size), dtype=int)

# 3. Rellenamos la matriz encendiendo el "1" correspondiente
for i, word in enumerate(sentence):
    if word in word_to_idx: # Verificamos que la palabra exista en el vocabulario
        vocab_index = word_to_idx[word]
        one_hot_matrix[i, vocab_index] = 1

print("Diccionario (Índice):", word_to_idx)
print("\nMatriz One-Hot resultante:")
print(one_hot_matrix)

Diccionario (Índice): {'cat': 0, 'sat': 1, 'mat': 2, 'the': 3}

Matriz One-Hot resultante:
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


## Actividad 2 — Similitud coseno

Implementa `cosine_similarity(a, b)` para vectores 1D y compara dos palabras usando sus filas one-hot (esperado: 0 o 1). Luego discute por qué one-hot no captura similitud semántica.


In [2]:
import numpy as np

# TODO: cosine_similarity
def cosine_similarity(a, b):
    # Calculamos el producto punto
    producto_punto = np.dot(a, b)
    # Calculamos las magnitudes (norma L2)
    norma_a = np.linalg.norm(a)
    norma_b = np.linalg.norm(b)
    
    # Evitamos la división por cero por seguridad
    if norma_a == 0 or norma_b == 0:
        return 0.0
        
    return producto_punto / (norma_a * norma_b)

# TODO: pick two rows from your one-hot matrix
# Recreamos unas filas one-hot simulando el vocabulario: ["perro", "gato", "coche"]
v_perro = np.array([1, 0, 0])
v_gato  = np.array([0, 1, 0])

# 1. Comparamos la misma palabra
sim_identica = cosine_similarity(v_perro, v_perro)
print(f"Similitud entre la misma palabra (perro, perro): {sim_identica}")

# 2. Comparamos dos palabras diferentes
sim_distinta = cosine_similarity(v_perro, v_gato)
print(f"Similitud entre palabras distintas (perro, gato): {sim_distinta}")

Similitud entre la misma palabra (perro, perro): 1.0
Similitud entre palabras distintas (perro, gato): 0.0


## Actividad 3 — Ventana con Gensim (lectura + entrenamiento mínimo)

Entrena un `Word2Vec` minúsculo sobre `sentences` (lista de listas de tokens) con `vector_size=8`, `window=2`, `min_count=1`. Imprime el vector de una palabra y la similitud entre dos.

*Hint:* `from gensim.models import Word2Vec`.


In [3]:
from gensim.models import Word2Vec

sentences = [
    ["the", "cat", "sat", "on", "the", "mat"],
    ["the", "dog", "sat", "on", "the", "log"],
]

# 1. Entrenar el modelo Word2Vec con los parámetros solicitados
modelo = Word2Vec(sentences, vector_size=8, window=2, min_count=1)

# 2. Inspeccionar el vector de una palabra usando el atributo .wv (Word Vectors)
vector_gato = modelo.wv['cat']
print("Vector denso de la palabra 'cat':")
print(vector_gato)
print(f"(Tamaño del vector: {vector_gato.shape})\n")

# 3. Calcular la similitud del coseno entre dos palabras
similitud = modelo.wv.similarity('cat', 'dog')
print(f"Similitud semántica entre 'cat' y 'dog': {similitud:.4f}")


Vector denso de la palabra 'cat':
[ 0.06227572  0.11541429 -0.10197397  0.05619748 -0.05171345  0.0103067
  0.10623275 -0.05577721]
(Tamaño del vector: (8,))

Similitud semántica entre 'cat' y 'dog': -0.0908
