# EX_01 — Embeddings básicos (ejercicios)

**Notebook de referencia:** `notebook/01_Introduccion_NLP_Embeddings_Basicos.ipynb`

**Tiempo orientativo:** ~30 minutos.


## Actividad 1 — One-hot desde vocabulario

Dado un vocabulario fijo y una frase tokenizada en palabras, construye una matriz one-hot `(seq_len, vocab_size)` sin sklearn (solo NumPy).


In [1]:
import numpy as np

vocab = ["cat", "sat", "mat", "the"]
sentence = ["the", "cat", "sat"] 

# Construir diccionario de índices
word2idx = {w: i for i, w in enumerate(vocab)}

# Matriz One-hot de ceros (longitud_frase, tamaño_vocabulario)
one_hot = np.zeros((len(sentence), len(vocab)))

for i, word in enumerate(sentence):
    if word in word2idx:
        one_hot[i, word2idx[word]] = 1

print(one_hot)


[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## Actividad 2 — Similitud coseno

Implementa `cosine_similarity(a, b)` para vectores 1D y compara dos palabras usando sus filas one-hot (esperado: 0 o 1). Luego discute por qué one-hot no captura similitud semántica.


In [2]:
import numpy as np

# Fórmula del coseno usando NumPy
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# Comparamos "the" (índice 0) y "cat" (índice 1) de la matriz anterior
vec_the = one_hot[0]
vec_cat = one_hot[1]

print("Similitud:", cosine_similarity(vec_the, vec_cat))

# Explicación: Da 0.0 porque los vectores one-hot son siempre ortogonales entre sí. 
# No capturan relación semántica, solo presencia/ausencia exacta en un índice.

Similitud: 0.0


## Actividad 3 — Ventana con Gensim (lectura + entrenamiento mínimo)

Entrena un `Word2Vec` minúsculo sobre `sentences` (lista de listas de tokens) con `vector_size=8`, `window=2`, `min_count=1`. Imprime el vector de una palabra y la similitud entre dos.

*Hint:* `from gensim.models import Word2Vec`.


In [3]:
from gensim.models import Word2Vec

sentences = [
    ["the", "cat", "sat", "on", "the", "mat"],
    ["the", "dog", "sat", "on", "the", "log"],
]

model = Word2Vec(sentences, vector_size=8, window=2, min_count=1)

print("Vector para 'cat':\n", model.wv['cat'])
print("Similitud entre 'cat' y 'dog':", model.wv.similarity('cat', 'dog'))

Vector para 'cat':
 [ 0.06227572  0.11541429 -0.10197397  0.05619748 -0.05171345  0.0103067
  0.10623275 -0.05577721]
Similitud entre 'cat' y 'dog': -0.09075314
